language: node_js
node_js:
- 10.15.3
script:
- npm test
before_deploy:
- openssl aes-256-cbc -K $encrypted_7892896c2e12_key -iv $encrypted_7892896c2e12_iv
  -in light-sail-cuckoo-plus.pem.enc -out light-sail-cuckoo-plus.pem -d
- eval "$(ssh-agent -s)"
- chmod 600 light-sail-cuckoo-plus.pem
- ssh-add light-sail-cuckoo-plus.pem
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
